server:
    port: 15451

    application:
        name: ichika-nacos
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848


spring:
    http:
        multipart:
            enabled: false
#            location: /Users/young/Desktop/ichika/
            location: /home/file/
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 300MB
    mvc:
        static-path-pattern: /**
    resources:
        static-locations: classpath:/static/, file:${spring.http.multipart.location}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://47.100.219.142:15432/ichika
        username: ichika
        password: ichika
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 100
        minIdle: 30
        maxActive: 200
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
    freemarker:
        suffix: .html
        cache: false
        charset: UTF-8
        allowRequestOverride: false
        allowSessionOverride: false
        checkTemplateLocation: false
        contentType: text/html
        exposeRequestAttributes: true
        exposeSessionAttributes: false
        templateEncoding: UTF-8
        settings:
            template_update_delay: 0
            default_encoding: UTF-8
            classic_compatible: true
            locale: zh_CN
            date_format: yyyy-MM-dd
            time_format: HH:mm:ss
            datetime_format: yyyy-MM-dd HH:mm:ss
            auto_import: spring.ftl as s
        devtools:
            restart:
                additional-paths: target/classes/
swagger:
    enabled: true
    base-path: /**
    exclude-path: /error, /ops/**
    base-package: com.ichika.api
